version: '3.3'

services:
  db:
    container_name: postgres
    image: postgres:16.3
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=javier
      - POSTGRES_PASSWORD=12345
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.6
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    restart: always
