version: '3.3'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=javier
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
