version: '3.3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=my_store
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
